import platform

ESC = b'\x1b\x1b'
if platform.system().lower() == 'windows':
    WIN_Z_LINUX_D = b'\x1a'
    BACKSPACE = b'\x08'
    DEL = b'\xe0S'
    UP = b'\xe0H'
    DOWN = b'\xe0P'
    LEFT = b'\xe0K'
    RIGHT = b'\xe0M'
    HOME = b'\xe0G'
    END = b'\xe0O'
    CTRL_LEFT = b'\xe0s'
    CTRL_RIGHT = b'\xe0t'
    CTRL_BACKSPACE = b'\x7f'
    CTRL_DELETE =  b'\xe0\x93'
    CTRL_C = b'\x03'
else:
    WIN_Z_LINUX_D = b'\x04'
    BACKSPACE = b'\x7f'
    DEL = b'\x1b[3~'
    UP = b'\xe0H'
    DOWN = b'\xe0P'
    LEFT = b'\xe0K'
    RIGHT = b'\xe0M'
    HOME = b'\xe0G'
    END = b'\xe0O'
    CTRL_LEFT = b'\xe0s'
    CTRL_RIGHT = b'\xe0t'
    CTRL_BACKSPACE = b'\x7f'
    CTRL_DELETE =  b'\xe0\x93'
    CTRL_C = b'\x03'
